// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyqozlofyngahpslmwti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5cW96bG9meW5nYWhwc2xtd3RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwNzY2NTQsImV4cCI6MjA1MTY1MjY1NH0.R1Xn9x3bzKgKf1Ek0Nz1_PYFk1fa9d_MhbdgO_iuHtg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);